### ISSUE TITLE
Keeps asking me for login, though I asked it to remember

### ISSUE THREAD

**Issue by asgerhallas** [mazkolain-zz/spotimc#22]
Hi,

I have an issue, where it keeps asking me for password each time I start the add-on though I check the Remember me checkbox. 

I'm on alpha4.

//Asger

**Comment by mazkolain-zz** [comment]
It's a known issue listed on the [FAQ](https://github.com/mazkolain/spotimc/wiki/FAQ), and probably related to some kind of unclean shutdown that affects subsequent session initializations (on the same process).

Running the addon on a different process space than XBMC would probably solve the issue, but it's somewhat hard to achieve right now.

**Comment by asgerhallas** [comment]
Oh, sorry I didn't see the FAQ. 

Let me know if there's is anything I can do :)

**Comment by asgerhallas** [comment]
I'm sorry, but looking at the FAQ now, I actually don't see it mentioned? Am I going blind, or is it moved?

**Comment by mazkolain-zz** [comment]
Sorry, I forgot to mention that it's related to the first issue on the FAQ.

The previously mentioned unclean shutdown seems to prevent libspotify from reading the stored credentials, and that's why it asks for the password again. Restarting XBMC frees the open session and everything works as it should (until the next initialization inside the same process).

I suspect that It's related to some uncollectable garbage cycle of python objects. I'll make some tests to avoid use of python destructors on the libspotify bindings, and hopefully the garbage cycle issues should be gone.

**Comment by mazkolain-zz** [comment]
Closing this issue. Fixed on the main branch.
