### ISSUE TITLE
Support arm version of XBMC

### ISSUE THREAD

**Issue by dereulenspiegel** [mazkolain-zz/spotimc#38]
Since the Raspberry Pi becomes more and more available and XBMC runs quite usable on it, it would be great to see this plugin work also on arm versions of XBMX so we can use this plugin on OpenElec on the Raspberry Pi for example.

**Comment by mazkolain-zz** [comment]
Hi @dereulenspiegel,

ARM support is on my future to-do list, but first I have to refactor the library loading code in order to support on the fly dependency downloads, instead of bundling all the libpsotify variants (Linux, OSX, Windows) on the same package.

Adding ARM support right now would make the download size grow from 7M to ~10M, which is not quite optimal.

Anyway, thanks for creating the issue!

**Comment by henricook** [comment]
I second this, after "playing video" this is my top desired feature on my new raspberry pi / openelec setup

**Comment by arkan** [comment]
Any news ? 

It would be great to have a version working with the Raspberry :-)

**Comment by leeb1986** [comment]
XBMC works great on raspberry pi.  Would love this addon to integrate spotify to complete my setup!!

**Comment by suprnova32** [comment]
The only thing you need to do to get this working is replace the libspotify.so from the dll/linux/x86 folder with this one: http://developer.spotify.com/download/libspotify/libspotify-10.1.16-Linux-armv6-release.tar.gz

I got my working today!

**Comment by mazkolain-zz** [comment]
Hi @supernova32, I just merged your patches. Thank you!

Nevertheless, my plan is to implement some sort of external library donwloads in the future, because the Spotimc's package size is getting bigger as we add support for more platforms.
