### ISSUE TITLE
Error led!: mazkolain-spotimc-2ca76e5

### ISSUE THREAD

**Issue by olexbmc** [mazkolain-zz/spotimc#64]
Hi :-)

can anyone help?

I get this 

"Error led!: mazkolain-spotimc-2ca76e5" 

...every time I start Spotimc in xbmc eden and can´t get further. It go on spinning for ever and I have to close xbmc manually. I have windows 7 Enterprise and of course mce 7 on my computer.

**Comment by mazkolain-zz** [comment]
You probably downloaded the package using Github's "donwload as..." option on the download page. These packages are not valid, since they don't include some binary dependencies (such as third party python libs or the libspotify dlls).

The valid download packages are the ones on the lower part of the github donwload page:
https://github.com/mazkolain/spotimc/downloads#uploaded_downloads

**Comment by olexbmc** [comment]
I have tried several downloads on the page you suggested and get the same message - so it did not work ;-( I have even deleted xbmc and installed it again - nothing seems to work.

Is it possible to uninstall spotimc inside xbmc?

**Comment by mazkolain-zz** [comment]
You can uninstall Spotimc from it's info dialog.

Anyway, I would be happy if you could send me a pastebin of the log file after the crash. I initially thought about the invalid downloads because of the error string.

**Comment by olexbmc** [comment]
I have deleted Spotimc inside xbmc and now it works fine :-) Many tanks for your help. It´s a fantastic and great plugin :-)

**Comment by olexbmc** [comment]
Hi

Can any one help me write a script to make "lm remote" run "script.audio.spotimc" after it has open XBMC?

**Comment by mazkolain-zz** [comment]
Closing this issue as fixed.

@olexbmc: Regarding your "one month old" side question (sorry for the delay), don't have any clues how to do it. I would suggest asking this same question on the XBMC forums:
http://forum.xbmc.org/forumdisplay.php?fid=110
