### ISSUE TITLE
Show notification for error 409

### ISSUE THREAD

**Issue by homburg** [mazkolain-zz/spotimc#68]
I have previously activated a premium subscription and used with spotimc.

Recently my payment failed, and the subscription reverted to a free account.

When I start spotimc with a free account, I'm presented with the Interface including the menus: "New Stuff", "Playslists", "Search" "More...", "Exit"
But the main area only shows a "spinner" indefinitly.

I could only get the error from the xbmc.log file:
`NOTICE: libspotify log: 11:07:04.753 E [ap:4097] Connection error:  409`

It would be helpful to have a notification from the gui, that the account does not have a "premium" subscription.

**Comment by homburg** [comment]
Also there was really no way to exit spotimc without restarting xbmc

**Comment by homburg** [comment]
Ps. I was using version 1.0-beta1, this might invalidate the issue :-)

**Comment by mazkolain-zz** [comment]
Hi,

Thanks for reporting and for all the useful information.

It seems to be hard to detect the account's subscription status, since the 409 error code is not directly available through the API. I could parse the log records, but the result would be some bunch of quirky code that I'll rather want to avoid.

I've created an additional account to test this issue with, and I'm waiting for it's premium subscription to expire. Sadly it will happen on the next 30 days, so I'll have to wait :(
