### ISSUE TITLE
Improvements & Recommendations

### ISSUE THREAD

**Issue by ghost** [mazkolain-zz/spotimc#70]
Hi 
First of all, thank-you for providing the best Spotify experience so far within XBMC.  I have been using your addon for quite a few months and love it.  Below is a list I have come up with that you may be interested in to further improve the overall experience.

Closing the addon:
When closing the addon when music is playing, the music hangs for about 20 seconds or so (like a scratched CD).  If there is a fix for this, is it also possible to make the addon close instantly?

Pressing "Stop" on the Microsoft MCE Remote makes the addon unusable.

Ability to run Spotimc in the background:
Just like all the other components within XBMC (TV Shows, Music, Movies etc.)  is it possible to allow Spotimc to run in the background without shutting down the addon? So for instance if I navigated away to the "Settings" tab and wanted to make a few changes, the music would keep on playing, then when I was done I could go back to spotimc without needing to re-open the addon.  

Skin Compatible:
Another great improvement that could be made would be the ability for skins to take control of the interface.  So the whole Spotimc experience would be the same as other aspects of the user customized XBMC Interface.

Control of Playlists:
Features that would be great to add to spotimc that already exist within the desktop software are, the ability to add/modify playlists/add to playlists/search for other playlists, radio feature, being able to sort the music in different orders.  

Have the ability to select a different output device:
My media center is my central point to my multi zone setup.  I would love the ability to select a different audio output over the XBMC set output device.  For instance being able to set spotimc to analog while the rest of XBMC would be HDMI.  This would allow me to distribute spotimc throughout my zones rather than be limited to the media room.  I also prefer the sound my amplifier produces on  the analog inputs over HDMI for music playback.  

Issues with playback:
Spotimc has the tenancy to skip to the next song during playback, also it seems to be more bandwidth hungry when compared to the desktop software.  In Spotimc the music hangs at times as if there isn't a sufficient internet connection.  I don't believe the issue is with Spotify as i don't experience this when using the desktop software.  

I have no understanding of software development, therefor don't understand if these requests are achievable within XBMC, or understand even how difficult it could be to achieve these requests, If they are at all possible. I would love these features/improvements to be incorporated into your addon.  Once again thank-you for your efforts so far, regardless of my comments above you have still produced an awesome addon, and the best Spotify addon for XBMC by far!  (I know as I have tried them all)

Cheers Kenton :)

**Comment by mazkolain-zz** [comment]
Hi Kenton,

Sorry for the delayed answers, but here are my thoughts on the issues you pointed out:
1. **Closing the addon:**
   The scratched CD issue was fixed in beta1, perhaps you are running an old version of Spotimc?
   Regarding the close delay, there isn't too much I can do here. When the logout process is started, I must wait for libspotify to notify that it's done. Exitting the app without waiting for libspotify may cause data loss (settings, cached tracks, etc.). Anyway, it's true that sometimes it takes long to exit the addon, but most of the delay is due to Spotimc waiting for libspotify to tell that it's ready to exit.
2. **Ability to run Spotimc in the background:**
   That's a pretty much requested feature (see #28), but sadly would require a revamp of the whole codebase of Spotimc (as far as I know), which is not achievable by now (in terms of required effort).
3. **Skin Compatible:**
   It's true that Spotimc could have been developed as a plugin (using XBMC's directory structure) rather than as a script (like now), but there are some benefits of doing that:
   - Full control of the GUI presentation (and the abbility to have a main menu, which is quite handy).
   - You know that you are inside Spotimc. Plugins are very useful, but you may get lost sometimes on the directory structure (you don't know whether you are inside a plugin or on some filesystem folder, etc.). For non tech savvy users it's pretty easy to get lost.
     There are of course many disadvantages of making it as a script, but in my opinion the benefits overcome the drawbacks.
4. **Control of Playlists:**
   That's completely true. I also miss the possibility of adding/removing items to playlists, or even sorting them. That's a pretty essential feature, that will hopefully go into future releases.
5. **Have the ability to select a different output device:**
   I feel that this should be implemented on XBMC's side. There are some XBMC patches around that provide this feature. Try googling for "xbmc dual audio output", and it should bring up many results.
6. **Issues with playback:**
   Ahh, the old song skipping issue :) This was fixed long ago back on alpha5 days, so definitely you must be running an old version of Spotimc!
   The bandwidth issue could be related to the fact that Spotimc's cache isn't full enought. The official client probably ran for more time than Spotimc, and thus, had more chances to fill up it's caches (and didn't required as many requests as Spotimc to Spotify's servers).

And many thanks for your feedback! Every user request helps making Spotimc better and better (sadly not all requests can be satisfied).

Regards,

Mikel
