### ISSUE TITLE
Spotimc hangs after a while

### ISSUE THREAD

**Issue by donshoarma** [mazkolain-zz/spotimc#75]
First of all thanks for the addon in xbmc!!! one of the main reasons for me to build my first htpc.

When using spotimc in my eden xbmc the music starts to hang after a while. I have the fealing that spotimc eats up my entire internet connection, this because while spotimc was having trouble the response of my connection was realy slow. After stopping spotimc everything went back to normal. This problem does not occur when using the standard (linux) client on the same machine.

If you require more information concerning my environment or the issue feel free to contact me.

**Comment by mazkolain-zz** [comment]
Hi,

I've noticed this issue recently too. If I'm not wrong, when this happens XBMC will eat lots of CPU and the log file should start to grow rapidly. Usually the log is flooded with messages like "this track cannot be played" and the like.

This could be related to the fact that some network error is not handled properly by Spotimc, letting XBMC go wild and request the rest of the playlist which is not available. As said, this is probably due to the fact that the connection went offline temporarily (due to a transient error), and no action is taken by Spotimc to notice XBMC of this condition (perhaps pausing playback until the connection is back online...).

Anyway, I would like to see a log file of this, just to be sure that we are talking about the same problem.

Thanks for reporting!

**Comment by donshoarma** [comment]
Thanks for your response. I tried to reproduce the error, but it has not
happened again. Everything works fine atm.

When it happens again I will post the log. But for now, thanks for the
great add-on we use it almost every day!

**Comment by mazkolain-zz** [comment]
Closing this issue, as it should be already resolved on the current development version.
