### ISSUE TITLE
Skipping to next track keeps skipping forever

### ISSUE THREAD

**Issue by protyposis** [mazkolain-zz/spotimc#92]
I'm running 1.0-beta3 on a fresh Frodo final install on Win7 x86. When I want to skip a track, either with the MCE remote or keyboard right arrow, it just keeps on skipping, playing a few seconds of the track (probably until the next track beginning is buffered), then skips to the next, and so on. I need to stop playback to get out of that loop and then restart the playlist, which is annoying if I play in shuffle mode and have to listen to the same tracks over and over again. Anybody else experiencing this issue?

**Comment by harry101** [comment]
Just want do confirm this problem. Installed Frodo on Windows 8 with 1.0 beta3. Everythings works fine until I open Karaoke-view. The first song goes fine, but from the next song it is a skipping bonanza. What ever I do the app hangs, lags and skip from song to song in the playlist. It do plays 1 - 2 second of every song before it goes to the next song, but I have to force Frodo down and restart to get it to work right again. Still as long as I keep away from "Karaoke" it looks like it works fine.

**Comment by protyposis** [comment]
@harry101, what do you mean with "karaoke view"? The fullscreen visualizer view which can also display the lyrics? If so, this problem is also solved in the current github code... at least for me the problem is gone :)

**Comment by harry101** [comment]
Hi. I have to admit that I'm quite new to xbmc and spotimc so yes what I called "Karaoke view" is the Fullscreen visualizer with lyrics. I have installed the the 1.0 beta3 from the zip and it is that one that don't work, but is there a more recent version that I don't know about? Im also a new to all this Github stuff and I got the link from http://forum.xbmc.org/showthread.php?tid=125147
Thanks for your feedback!
Br Harald

**Comment by protyposis** [comment]
I compiled the plugin from the current sources... there's no newer version released yet, but I'm pretty sure this problem is solved! You'll just have to wait until the next official release.

**Comment by thatguy188** [comment]
I have the same issue running the latest beta. Works fine however in full screen mode it'll play each song for a second then goes to next track. The problem I definitely still there. Wish it was resolvable as the full screen mode is GORGEOUS

**Comment by mazkolain-zz** [comment]
@thatguy188, @harry101: Finally I was able to reproduce the issue (and figure out a possible workaround).

**The explanation:**
Indeed, the issue is caused by the lyrics script on it's attempt to analyze the audio stream (searching possible embedded lyric data on it). For this, it opens an additional stream to the current track being played, which causes the stream already opened by XBMC to close. This is due to the internal design of libspotify, which does not allow opening simultaneous streams in parallel.

**The workaround:**
You'll have to change an specific setting on the lyrics script in order to avoid this issue (tested with script.cu.lrclyrics). On the lyrics script's settings page, make sure the option "Search for embedded lyrics" of the "Scrapers" tab is disabled.

I'll talk with the lyrics script developer and see if we can find a solution, but in the meantime you can try with the above setting change.
