### ISSUE TITLE
quitting xbmc while in spotifymc killed the whole NAS

### ISSUE THREAD

**Issue by Silverdream** [mazkolain-zz/spotimc#96]
Hello

I have a QNAP NAS TS-469L with HD Station, wiich includes an XBMC.
The installation of Spotimc went perfect and music sound was perfect, untill i wanted to quit XBMC. The spotimc window froze on the screen, and nothing more. I tried enter the NAS Admin panel, and was met with:

404 Not Found
The path '/' was not found.

Traceback (most recent call last):
  File "/root/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cprequest.py", line 656, in respond
    response.body = self.handler()
  File "/root/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/lib/encoding.py", line 188, in __call__
    self.body = self.oldhandler(_args, *_kwargs)
  File "/root/.xbmc/addons/script.audio.spotimc/resources/libs/CherryPy.egg/cherrypy/_cperror.py", line 386, in __call__
    raise self
NotFound: (404, "The path '/' was not found.")
Powered by CherryPy 3.2.2

If this is something that can be fixed, and you need more details, log files from somewhere, tell where and i can provide.

**Comment by mazkolain-zz** [comment]
Hello,

The freeze you experienced is a known issue that happens sporadically and affects Spotimc beta3 running Frodo. There's already a fix for this issue and will be included on the next release, but in the meantime you could try stopping playback manually before exitting Spotimc.

Regarding the NAS admin panel issue, Spotimc starts an embedded web server to serve spotify images and track streams to XBMC. It seems that this embedded server and the NAS admin interface are listening on the same port (8080), so Spotimc may be interfering to the latter one. Anyway, this is strange because Spotimc first checks if the port is available for listening (will check ports 8080-8090), so in theory it won't occupy a port number which is already in use (by the NAS admin panel for example).

Perhaps the NAS log files will give more details on this issue. It will probably complain that there's something wrong with the admin interface's port number...
